-- PARTE A: clienti, utenti, catalogo, commesse (16+14+47+16 = 93 righe)
DELETE FROM commesse WHERE codice = 'TEST001';

-- ============ CLIENTI ============
-- 16 record

INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL824', 'ILE DE BEAUTE SRL', 'Società', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL823', 'BOFFOLI', 'Privato/Altro', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL822', 'BESSO', 'Privato/Altro', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL821', 'DEL VECCHIO TRIVELLAZIONI SRL', 'Società', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL820', 'DILELLA INVEST', 'Privato/Altro', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL819', 'FARMACIA SAN NICOLA SRL', 'Società', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL818', 'MININNI', 'Privato/Altro', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL817', 'POLIGNANO', 'Privato/Altro', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL814', '814_HAMBURGHERIA RIO_ MAURIZIO FOGGETTI', 'Privato/Altro', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL812', 'FIN MARE SRL', 'Società', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL811', 'LEPORE GIGLIELMO SRL', 'Società', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL808', 'TERLIZZI SRL', 'Società', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL806', 'NICCOLO CARLOTTA', 'Privato/Altro', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL805', 'MISERICORDIA SURGERY', 'Privato/Altro', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL803', 'SEBAGO', 'Privato/Altro', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO clienti (id, denominazione, tipo_cliente, codice_fiscale, partita_iva, email, telefono, indirizzo, note) VALUES ('CL800', 'MARTOCCIA MARCELLO', 'Privato/Altro', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;

-- ============ UTENTI ============
-- 14 record (solo colonne esistenti: nome, interno_esterno, costo_orario)
-- Usa WHERE NOT EXISTS per idempotenza (non c'e' UNIQUE su nome)
-- NOTA: se questi utenti esistono gia' nel DB (con email/password), le righe vengono saltate.

INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'LUCA', 'Interno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'LUCA');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'RAFFAELE', 'Interno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'RAFFAELE');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'ANNA', 'Interno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'ANNA');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'BLERTA', 'Interno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'BLERTA');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'CARLO', 'Interno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'CARLO');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'ENRICO', 'Interno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'ENRICO');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'TRAGNI', 'Esterno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'TRAGNI');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'NICOLA', 'Interno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'NICOLA');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'VITTORIO', 'Interno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'VITTORIO');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'FRANCESCO', 'Interno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'FRANCESCO');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'SILVIA', 'Interno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'SILVIA');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'PINO', 'Interno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'PINO');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'ROSSIGNOLI', 'Esterno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'ROSSIGNOLI');
INSERT INTO utenti (nome, interno_esterno, costo_orario) SELECT 'ALTAMURA', 'Esterno', 30.00 WHERE NOT EXISTS (SELECT 1 FROM utenti WHERE nome = 'ALTAMURA');

-- ============ CATALOGO_PRESTAZIONI ============
-- 47 record

INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P001', NULL, 'STUDIO DI FATTIBILITA''', 'Generale', 'Consulenza tecnica', TRUE, 1, 'STUDIO_DI_FATTIBILITA') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P002', NULL, 'RILIEVI E SOPRALLUOGHI TECNICI', 'Generale', 'Consulenza tecnica', TRUE, 2, 'RILIEVI_E_SOPRALLUOGHI_TECNICI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P003', NULL, 'ACCESSO ATTI', 'Generale', 'Consulenza tecnica', TRUE, 3, 'ACCESSO_ATTI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P004', NULL, 'PROGETTAZIONE ARCHITETTONICA DEFINITIVA', 'Edilizia', 'Edilizia privata', TRUE, 4, 'PROGETTAZIONE_ARCHITETTONICA_DEFINITIVA') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P005', NULL, 'PROGETTO STRUTTURE', 'Generale', 'Consulenza tecnica', TRUE, 5, 'PROGETTO_STRUTTURE') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P006', NULL, 'RENDER PROGETTO', 'Generale', 'Consulenza tecnica', TRUE, 6, 'RENDER_PROGETTO') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P007', NULL, 'BOOK PROGETTO', 'Generale', 'Consulenza tecnica', TRUE, 7, 'BOOK_PROGETTO') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P008', NULL, 'BOOK VENDITE', 'Generale', 'Consulenza tecnica', TRUE, 8, 'BOOK_VENDITE') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P009', NULL, 'ELABORATI PRATICA EDILIZIA', 'Edilizia', 'Edilizia privata', TRUE, 9, 'ELABORATI_PRATICA_EDILIZIA') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P010', NULL, 'RELAZIONE TECNICA', 'Generale', 'Consulenza tecnica', TRUE, 10, 'RELAZIONE_TECNICA') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P011', NULL, 'PROTOCOLLO ITACA', 'Energetica', 'Energetica', TRUE, 11, 'PROTOCOLLO_ITACA') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P012', NULL, 'OCCUP SUOLO FISSO /SEMPLIFICATO', 'Commerciale / autorizzativa', 'Commerciale / SUAP', TRUE, 12, 'OCCUP_SUOLO_FISSO_SEMPLIFICATO') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P013', NULL, 'OCCUP SUOLO PER LAVORI', 'Commerciale / autorizzativa', 'Commerciale / SUAP', TRUE, 13, 'OCCUP_SUOLO_PER_LAVORI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P014', NULL, 'CILA/SCIA/ EDILIZIA', 'Edilizia', 'Edilizia privata', TRUE, 14, 'CILA_SCIA_EDILIZIA') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P015', NULL, 'SCIA ALT. PDC/PDL', 'Edilizia', 'Edilizia privata', TRUE, 15, 'SCIA_ALT_PDC_PDL') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P016', NULL, 'PRATICA SUAP', 'Commerciale / autorizzativa', 'Commerciale / SUAP', TRUE, 16, 'PRATICA_SUAP') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P017', NULL, 'PRATICA PATRIMONIO', 'Generale', 'Consulenza tecnica', TRUE, 17, 'PRATICA_PATRIMONIO') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P018', NULL, 'PRATICA PAESAGGISTICA', 'Generale', 'Consulenza tecnica', TRUE, 18, 'PRATICA_PAESAGGISTICA') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P019', NULL, 'PRATICA SABAP', 'Generale', 'Consulenza tecnica', TRUE, 19, 'PRATICA_SABAP') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P020', NULL, 'PRATICA ASL', 'Commerciale / autorizzativa', 'Commerciale / SUAP', TRUE, 20, 'PRATICA_ASL') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P021', NULL, 'PROGETTAZIONE ARCHITETTONICA ESECUTIVA', 'Edilizia', 'Edilizia privata', TRUE, 21, 'PROGETTAZIONE_ARCHITETTONICA_ESECUTIVA') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P022', NULL, 'IMPIANTI ELETTRICI', 'Impianti', 'Impianti', TRUE, 22, 'IMPIANTI_ELETTRICI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P023', NULL, 'IMPIANTI TERMO IDRAULICI', 'Impianti', 'Impianti', TRUE, 23, 'IMPIANTI_TERMO_IDRAULICI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P024', NULL, 'SICUREZZA IN FASE DI PROGETTAZIONE', 'Sicurezza', 'Sicurezza', TRUE, 24, 'SICUREZZA_IN_FASE_DI_PROGETTAZIONE') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P025', NULL, 'COMPUTI METRICI', 'Generale', 'Consulenza tecnica', TRUE, 25, 'COMPUTI_METRICI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P026', NULL, 'SICUREZZA IN FASE DI ESECUZIONE', 'Sicurezza', 'Sicurezza', TRUE, 26, 'SICUREZZA_IN_FASE_DI_ESECUZIONE') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P027', NULL, 'DIREZIONE LAVORI', 'Direzione lavori', 'Direzione lavori', TRUE, 27, 'DIREZIONE_LAVORI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P028', NULL, 'DIREZIONE OPERE STRUTTURALI', 'Direzione lavori', 'Direzione lavori', TRUE, 28, 'DIREZIONE_OPERE_STRUTTURALI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P029', NULL, 'DIREZIONE IMPIANTI ELETTRICI', 'Impianti', 'Impianti', TRUE, 29, 'DIREZIONE_IMPIANTI_ELETTRICI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P030', NULL, 'DIREZIONE IMPIANTI TERMO IDRAULICI', 'Impianti', 'Impianti', TRUE, 30, 'DIREZIONE_IMPIANTI_TERMO_IDRAULICI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P031', NULL, 'CATASTO INIZIALE DOCFA E EL.PLANIMETRICO', 'Catasto', 'Catasto', TRUE, 31, 'CATASTO_INIZIALE_DOCFA_E_EL_PLANIMETRICO') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P032', NULL, 'CATASTO FINALE', 'Catasto', 'Catasto', TRUE, 32, 'CATASTO_FINALE') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P033', NULL, 'ELABORATI PUBBLICITA''', 'Commerciale / autorizzativa', 'Commerciale / SUAP', TRUE, 33, 'ELABORATI_PUBBLICITA') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P034', NULL, 'SCIA PUBBLICITA''', 'Commerciale / autorizzativa', 'Commerciale / SUAP', TRUE, 34, 'SCIA_PUBBLICITA') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P035', NULL, 'VV FF (SCIA/CPI)', 'Edilizia', 'Edilizia privata', TRUE, 35, 'VV_FF_SCIA_CPI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P036', NULL, 'COLLAUDO STATICO', 'Generale', 'Consulenza tecnica', TRUE, 36, 'COLLAUDO_STATICO') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P037', NULL, 'PASSO CARRABILE', 'Generale', 'Consulenza tecnica', TRUE, 37, 'PASSO_CARRABILE') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P038', NULL, 'APE', 'Energetica', 'Energetica', TRUE, 38, 'APE') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P039', NULL, 'FINE LAVORI', 'Edilizia', 'Edilizia privata', TRUE, 39, 'FINE_LAVORI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P040', NULL, 'SCIA AGIBILITA''', 'Edilizia', 'Edilizia privata', TRUE, 40, 'SCIA_AGIBILITA') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P041', NULL, 'CILA/SCIA/ EDILIZIA/ PDC', 'Edilizia', 'Edilizia privata', TRUE, 41, 'CILA_SCIA_EDILIZIA_PDC') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P042', NULL, 'SUPPORTO SCELTA MATERIALI', 'Generale', 'Consulenza tecnica', TRUE, 42, 'SUPPORTO_SCELTA_MATERIALI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P043', NULL, 'PERMESSO DI COSTRUIRE', 'Generale', 'Consulenza tecnica', TRUE, 43, 'PERMESSO_DI_COSTRUIRE') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P044', NULL, 'PRATICA ZES', 'Generale', 'Consulenza tecnica', TRUE, 44, 'PRATICA_ZES') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P045', NULL, 'SCELTA MATERIALI EDILI PRESSO FORNITORI', 'Generale', 'Consulenza tecnica', TRUE, 45, 'SCELTA_MATERIALI_EDILI_PRESSO_FORNITORI') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P046', NULL, 'PROGETTAZIONE E SCELTA ILLUMINOTECNICA', 'Generale', 'Consulenza tecnica', TRUE, 46, 'PROGETTAZIONE_E_SCELTA_ILLUMINOTECNICA') ON CONFLICT (id) DO NOTHING;
INSERT INTO catalogo_prestazioni (id, codice, descrizione, categoria, area_pratica, attiva, ordinamento, chiave_normalizzata) VALUES ('P047', NULL, 'PROGETTAZIONE E SCELTA ARREDI', 'Generale', 'Consulenza tecnica', TRUE, 47, 'PROGETTAZIONE_E_SCELTA_ARREDI') ON CONFLICT (id) DO NOTHING;

-- ============ COMMESSE ============
-- 16 record

INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '824', 'ILE DE BEAUTE SRL', 'ILE DE BEAUTE SRL', 'CILA', NULL, 'Edilizia privata', 'CILA', 1500, 1500, NULL, 'Aperto', 'La mail risale al 30 marzo 2026', 'Da verificare', NULL, -70, 1500, NULL, 70 WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '824');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '823', 'BOFFOLI', 'BOFFOLI RIVA DEI TESSALI', 'SCIA MANUTENZIONE STRAORDINARIA', 'RIVA DEI TESSALI - CASTELLANETA MARINA', 'Edilizia privata', 'SCIA MANUTENZIONE STRAORDINARIA', NULL, NULL, NULL, 'Aperto', NULL, 'Mancante/Non firmato', 'CHIEDERE A VITTORIO E GEPPI', 0, NULL, NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '823');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '822', 'BESSO', 'BESSO - corso Vittorio Emanuele', 'ADEGUAMENTO LOCALE COMMERCIALE', 'CORSO VITTORIO EMANUELE_BARI', 'Commerciale / SUAP', 'ADEGUAMENTO LOCALE COMMERCIALE', 12000, 12000, NULL, 'Aperto', NULL, 'Mancante/Non firmato', 'CONTRATTO DA CHIUDERE IL 06/05/2026', 0, NULL, NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '822');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '821', 'DEL VECCHIO TRIVELLAZIONI SRL', 'DEL VECCHIO - Giovinazzo', 'CONTRACTOR', 'Giovinazzo', 'Contractor / gestione lavori', 'CONTRACTOR', 30000, 30000, NULL, 'Aperto', NULL, 'Firmato/Presente', NULL, 3000, 10000, 10000, 7000 WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '821');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '820', 'DILELLA INVEST', 'DILELLA INVEST STAZIONE DI SERVIZIO', 'STAZIONE DI SERVIZIO - VIA MAZZITELLI', 'BARI', 'Consulenza tecnica', 'STAZIONE DI SERVIZIO - VIA MAZZITELLI', NULL, NULL, NULL, 'Aperto', NULL, 'Mancante/Non firmato', NULL, NULL, NULL, NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '820');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '819', 'FARMACIA SAN NICOLA SRL', 'FARMACIA SAN NICOLA - C.SO CAVOUR', 'ADEGUAMENTO LOCALE COMMERCIALE', 'C.SO CAVOUR 53/A BARI', 'Commerciale / SUAP', 'ADEGUAMENTO LOCALE COMMERCIALE', 3000, 3000, NULL, 'Aperto', NULL, 'Firmato/Presente', 'Cartella assente sul NAS', 1500, 1500, 1500, NULL WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '819');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '818', 'MININNI', 'MININNI - VIA MAURO AMORUSO', 'MODIFICA SCALA', 'VIA MAURO AMORUSO', 'Consulenza tecnica', 'MODIFICA SCALA', NULL, NULL, NULL, 'Aperto', NULL, 'Mancante/Non firmato', 'CHIEDERE A CARLO | CARLO ED ENRICO HANNO FATTO UN RILIEVO E CARLO HA FATTO BOZZA MODIFICA SCALA', 0, NULL, NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '818');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '817', 'POLIGNANO', 'POLIGNANO', 'CAMBIO DESTINAZIONE D''USO E PROGETTAZIONE', 'CONTRADA VIA DE ROSSI', 'Consulenza tecnica', 'CAMBIO DESTINAZIONE D''USO E PROGETTAZIONE', 8000, 8000, NULL, 'Aperto', NULL, 'Firmato/Presente', 'Cartella assente sul NAS | La scheda è stata compilata con importi differenti dal contratto VEDERE CON ANNA', 3000, 3000, 3000, NULL WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '817');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '814', '814_HAMBURGHERIA RIO_ MAURIZIO FOGGETTI', 'HI HAMBURGHERIA', 'RISTRUTTURAZIONE LOCALE COMMERCIALE', 'VIA FANELLI 202/A7', 'Commerciale / SUAP', 'RISTRUTTURAZIONE LOCALE COMMERCIALE', 12000, 12000, NULL, 'Aperto', NULL, 'Mancante/Non firmato', 'contratto non firmato', 0, NULL, NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '814');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '812', 'FIN MARE SRL', 'FIN MARE SRL', 'CAMBIO DESTINAZIONE D''USO DA UFFICIO AD ABITAZIONE', 'BARI_VIA CONENNA, 28 (SANT''ANNA)_DE GENNARO', 'Consulenza tecnica', 'CAMBIO DESTINAZIONE D''USO DA UFFICIO AD ABITAZIONE', 2400, 2400, NULL, 'Aperto', NULL, 'Mancante/Non firmato', 'Emettere fattura', -70, NULL, NULL, 70 WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '812');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '811', 'LEPORE GIGLIELMO SRL', 'LEPORE GIGLIELMO SRL', 'NUOVE VILLE', 'VILLE S.SPIRITO', 'Consulenza tecnica', 'NUOVE VILLE', 100000, 100000, NULL, 'Aperto', NULL, 'Mancante/Non firmato', 'Cartella presente ma materiale assente', NULL, 100000, 100000, 100000 WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '811');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '808', 'TERLIZZI SRL', 'TERLIZZI SRL', 'RIQUALIFICAZIONE AREA PANE E POMODORO', 'PANE E POMODORO A BARI', 'Consulenza tecnica', 'RIQUALIFICAZIONE AREA PANE E POMODORO', 3000, 3000, NULL, 'Aperto', NULL, 'Firmato/Presente', 'Materiale assente (VEDERE CON ANNA IL CONTRATTO FIRMATO)', 765, 1500, 765, NULL WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '808');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '806', 'NICCOLO CARLOTTA', 'NICCOLO CARLOTTA - FASANO', 'CONTRACTOR', 'FASANO', 'Contractor / gestione lavori', 'CONTRACTOR', 482000, 482000, NULL, 'Aperto', NULL, 'Da verificare', NULL, 7695, 342695, 277695, NULL WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '806');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '805', 'MISERICORDIA SURGERY', 'MISERICORDIA SURGERY', 'NUOVA COSTRUZIONE DI POLIAMBULATORIO CHIRURGICO CON ZES', 'VIA ADRIATICO - BARI', 'Edilizia privata', 'NUOVA COSTRUZIONE DI POLIAMBULATORIO CHIRURGICO CON ZES', NULL, NULL, NULL, 'Aperto', NULL, 'Mancante/Non firmato', 'Manca contratto', NULL, NULL, NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '805');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '803', 'SEBAGO', 'SEBAGO_CLIMA', 'LAVORI DI IMPLEMENTAZIONE IMPIANTO CLIMA DEL 23/02/2026', 'VIA PUTIGNANI - BARI', 'Impianti', 'LAVORI DI IMPLEMENTAZIONE IMPIANTO CLIMA DEL 23/02/2026', 4400, 4400, NULL, 'Aperto', NULL, 'Firmato/Presente', 'MANCA IL PAGAMENTO DELLA FATTURA', 4400, 4400, NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '803');
INSERT INTO commesse (codice, cliente, titolo, oggetto, indirizzo_intervento, area_pratica, tipo_pratica, budget, importo_contratto, scadenza, stato, pm_assegnato, contratto_stato, note, cassa, totale_fatturato, totale_pagato, totale_spese) SELECT '800', 'MARTOCCIA MARCELLO', 'MARTOCCIA', 'RISTRUTTURAZIONE EDILIZIA', 'VIA DE LAURENTIS, 16 - BARI (10° PIANO)', 'Edilizia privata', 'RISTRUTTURAZIONE EDILIZIA', NULL, NULL, NULL, 'Aperto', NULL, 'Mancante/Non firmato', 'Manca contratto', 0, NULL, NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM commesse WHERE codice = '800');

